// Auto-generated by tools/gen_types.mjs. Do NOT edit manually.
/* eslint-disable */

// === Enums & Inputs ===

[object Object]
[object Object]

// === Indicators DTOs ===

[object Object]
[object Object]
[object Object]