// Generate .d.ts from Zod schemas in src/schemas.js
// Usage: node tools/gen_types.mjs
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { zodToTs } from 'zod-to-ts';
import {
  CandleTypeEnum,
  RenderChartSvgInputSchema,
  ChartPayloadSchema,
  GetIndicatorsDataSchema,
  GetIndicatorsMetaSchema,
} from '../src/schemas.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outPath = path.join(__dirname, '../src/types/schemas.generated.d.ts');

function section(title) {
  return `\n// === ${title} ===\n`;
}

const chunks = [];

chunks.push('// Auto-generated by tools/gen_types.mjs. Do NOT edit manually.');
chunks.push("/* eslint-disable */");

// Enums and inputs
chunks.push(section('Enums & Inputs'));
chunks.push(zodToTs(CandleTypeEnum, 'CandleType').node);
chunks.push(zodToTs(RenderChartSvgInputSchema, 'RenderChartSvgInput').node);

// Indicators
chunks.push(section('Indicators DTOs'));
chunks.push(zodToTs(ChartPayloadSchema, 'ChartPayload').node);
chunks.push(zodToTs(GetIndicatorsDataSchema, 'GetIndicatorsDataFromSchema').node);
chunks.push(zodToTs(GetIndicatorsMetaSchema, 'GetIndicatorsMetaFromSchema').node);

const content = chunks.join('\n');

await fs.mkdir(path.dirname(outPath), { recursive: true });
await fs.writeFile(outPath, content, 'utf8');
console.log(`Generated: ${path.relative(process.cwd(), outPath)}`);


